import { EventEmitter } from "node:events";
import { mkdir } from "node:fs/promises";
import { resolve } from "node:path";
import Database from "better-sqlite3";
import { TXLINE_API_BASE, loadTxlineCredentials, txlineRequest } from "./txline-client.js";

export const eventEmitter = new EventEmitter();
const DB_PATH = resolve(".data/matchflash.db");
type Fixture = { FixtureId:number; Participant1?:string; Participant2?:string; GameState?:unknown; StartTime?:unknown; [key:string]:unknown };
const fixtureId=(payload:unknown):number|undefined=>{if(!payload||typeof payload!=="object")return undefined;const record=payload as Record<string,unknown>;for(const key of ["FixtureId","fixtureId","fixture_id"]){if(Number.isSafeInteger(Number(record[key])))return Number(record[key])}return undefined};
function setup(){const d=new Database(DB_PATH);d.pragma("journal_mode = WAL");d.exec("CREATE TABLE IF NOT EXISTS fixtures (id INTEGER PRIMARY KEY, home_team TEXT, away_team TEXT, status TEXT, kickoff_at TEXT, raw_json TEXT NOT NULL); CREATE TABLE IF NOT EXISTS events (id INTEGER PRIMARY KEY, fixture_id INTEGER NOT NULL, type TEXT NOT NULL, payload_json TEXT NOT NULL, received_at TEXT NOT NULL);");return d}
function blocks(input:string){return input.replace(/\r/g,"").split("\n\n").map(x=>{const data=x.split("\n").filter(l=>l.startsWith("data:")).map(l=>l.slice(5).trim()).join("\n");return data?JSON.parse(data):null}).filter(Boolean)}
async function stream(kind:"odds"|"scores",id:number,d:Database.Database){let delay=1000;for(;;){try{const c=await loadTxlineCredentials();const r=await txlineRequest(`${TXLINE_API_BASE}/${kind}/stream?fixtureId=${id}`,c);if(!r.ok||!r.body)throw Error(`HTTP ${r.status}`);console.log(`STREAM_CONNECTED source=${kind} fixture_id=${id}`);delay=1000;const reader=r.body.pipeThrough(new TextDecoderStream()).getReader();let b="";for(;;){const x=await reader.read();if(x.done)throw Error("stream closed");b+=x.value;const parts=b.split("\n\n");b=parts.pop()??"";for(const raw of blocks(parts.join("\n\n"))){const fid=fixtureId(raw);if(fid!==id)continue;const info=d.prepare("INSERT INTO events (fixture_id,type,payload_json,received_at) VALUES (?,?,?,?)").run(fid,`${kind}_update`,JSON.stringify(raw),new Date().toISOString());eventEmitter.emit("event",{id:info.lastInsertRowid,fixtureId:fid,type:`${kind}_update`,payload:raw});console.log(`EVENT_PERSISTED source=${kind} fixture_id=${fid} payload=${JSON.stringify(raw)}`)}}}catch(e){console.error(`STREAM_RECONNECT source=${kind} fixture_id=${id} delay_ms=${delay} reason=${e instanceof Error?e.message:String(e)}`);await new Promise(r=>setTimeout(r,delay));delay=Math.min(delay*2,30000)}}}
async function main(){await mkdir(resolve(".data"),{recursive:true});const d=setup();const c=await loadTxlineCredentials();const r=await txlineRequest(`${TXLINE_API_BASE}/fixtures/snapshot`,c);if(!r.ok)throw Error(`fixture snapshot HTTP ${r.status}`);const fs=await r.json() as Fixture[];for(const f of fs)d.prepare("INSERT INTO fixtures (id,home_team,away_team,status,kickoff_at,raw_json) VALUES (?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET raw_json=excluded.raw_json").run(f.FixtureId,f.Participant1??null,f.Participant2??null,String(f.GameState??"unknown"),String(f.StartTime??""),JSON.stringify(f));console.log(`FIXTURE_SNAPSHOT count=${fs.length}`);const live=fs.filter(f=>Number(f.GameState)===2||Number(f.GameState)===3);if(!live.length)console.log("No live fixture — falling back to validation-proof / historical endpoint for verification.");for(const f of (live.length?live:fs).slice(0,1)){void stream("odds",f.FixtureId,d);void stream("scores",f.FixtureId,d)}}
void main().catch(e=>{console.error("INGEST_FATAL",e instanceof Error?e.message:String(e));process.exitCode=1});
